# Generated by Django 3.2.5 on 2022-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('f', 'failed'), ('s', 'success'), ('w', 'waiting')], default='w', max_length=1),
        ),
    ]
