# Generated by Django 3.2.5 on 2021-11-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
