# Generated by Django 3.2.5 on 2021-11-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_couponcode'),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='order_app.couponcode', verbose_name='کد تخفیف'),
        ),
    ]
