# Generated by Django 3.2.5 on 2021-07-10 22:26

import course_app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('image', models.ImageField(upload_to=course_app.models.upload_image_path, verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('level', models.CharField(choices=[('b', 'مبتدی'), ('m', 'متوسط'), ('a', 'پیشرفته'), ('bm', 'مبتدی تا متوسط'), ('ma', 'متوسط تا پیشرفته'), ('ba', 'مبتدی تا پیشرفته')], default='b', max_length=2, verbose_name='سطح دوره')),
                ('status', models.CharField(choices=[('d', 'پیشنویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ['-publish_time'],
            },
        ),
    ]
