# Generated by Django 3.2.5 on 2021-07-17 23:27

import course_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='عنوان در url')),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('position', models.IntegerField(default=0, verbose_name='اولویت قرارگیری')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('image', models.ImageField(upload_to=course_app.models.upload_image_path, verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('level', models.CharField(choices=[('b', 'مقدماتی'), ('m', 'متوسط'), ('a', 'پیشرفته'), ('bm', 'مقدماتی تا متوسط'), ('ma', 'متوسط تا پیشرفته'), ('ba', 'مقدماتی تا پیشرفته')], default='b', max_length=2, verbose_name='سطح دوره')),
                ('status', models.BooleanField(default=False, verbose_name='آیا نمایش داده شود؟')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='course_category', to='course_app.CourseCategory', verbose_name='دسته بندی')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ['-publish_time'],
            },
        ),
    ]
