# Generated by Django 3.2.5 on 2021-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('b', 'مقدماتی'), ('m', 'متوسط'), ('a', 'پیشرفته'), ('bm', 'مقدماتی تا متوسط'), ('ma', 'متوسط تا پیشرفته'), ('ba', 'مقدماتی تا پیشرفته')], default='b', max_length=2, verbose_name='سطح دوره'),
        ),
    ]
