# Generated by Django 3.2.5 on 2021-07-18 09:57

import course_app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('video', models.FileField(upload_to=course_app.models.upload_video_path, verbose_name='ویدیو')),
                ('position', models.PositiveIntegerField(default=0, unique=True, verbose_name='شماره جلسه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='course_app.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['position'],
            },
        ),
    ]
