# Generated by Django 3.2.5 on 2021-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='زمان ویدیو'),
        ),
    ]
