# Generated by Django 3.2.5 on 2021-07-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='آیا دوره تمام شده؟'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('mo', 'غیره')], default='fa', max_length=2, verbose_name='زبان دوره'),
        ),
    ]
