# Generated by Django 3.2.5 on 2021-07-21 11:12

import account_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(blank=True, unique=True, verbose_name='شماره تماس')),
                ('web_site', models.URLField(blank=True, verbose_name='آدرس وب سایت')),
                ('bio', models.TextField(blank=True, max_length=700, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(upload_to=account_app.models.upload_avatar_path, verbose_name='تصویر آواتار')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرفایل',
                'verbose_name_plural': 'پرفایل ها',
                'ordering': ['-create_time'],
            },
        ),
    ]
