# Generated by Django 3.2.5 on 2021-07-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-create_time'], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
