# Generated by Django 3.2.5 on 2021-07-21 11:29

import account_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20210721_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account_app.models.upload_avatar_path, verbose_name='تصویر آواتار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وب سایت'),
        ),
    ]
