# Generated by Django 3.2.5 on 2021-08-17 12:13

from django.db import migrations, models
import settings_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=300, verbose_name='عنوان سایت')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('instagram', models.CharField(max_length=300, verbose_name='آی دی اینساگرام')),
                ('twitter', models.CharField(max_length=300, verbose_name='آی دی توییتر')),
                ('youtube', models.CharField(max_length=300, verbose_name='آی دی یوتیوب')),
                ('site_favicon', models.ImageField(upload_to=settings_app.models.upload_image_path, verbose_name='آیکون هدر سایت')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-create_time'],
            },
        ),
    ]
